//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Verification2022Entities : DbContext
    {
        public Verification2022Entities()
            : base("name=Verification2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_College_Email> Tbl_College_Email { get; set; }
        public virtual DbSet<Tbl_Div_Details> Tbl_Div_Details { get; set; }
        public virtual DbSet<Tbl_Div_Login> Tbl_Div_Login { get; set; }
        public virtual DbSet<Tbl_HSC_Data> Tbl_HSC_Data { get; set; }
        public virtual DbSet<Tbl_HSC_Division_Block> Tbl_HSC_Division_Block { get; set; }
        public virtual DbSet<Tbl_HSC_Payment> Tbl_HSC_Payment { get; set; }
        public virtual DbSet<Tbl_HSC_Payment_Error> Tbl_HSC_Payment_Error { get; set; }
        public virtual DbSet<Tbl_HSC_Student_Subject> Tbl_HSC_Student_Subject { get; set; }
        public virtual DbSet<Tbl_HSC_SUB> Tbl_HSC_SUB { get; set; }
        public virtual DbSet<Tbl_HSC_UID> Tbl_HSC_UID { get; set; }
        public virtual DbSet<Tbl_HSC_Verification> Tbl_HSC_Verification { get; set; }
        public virtual DbSet<Tbl_HSC_Verification_Pri> Tbl_HSC_Verification_Pri { get; set; }
        public virtual DbSet<Tbl_Migration> Tbl_Migration { get; set; }
        public virtual DbSet<Tbl_Migration_Pri> Tbl_Migration_Pri { get; set; }
        public virtual DbSet<Tbl_OS_HSC> Tbl_OS_HSC { get; set; }
        public virtual DbSet<Tbl_OS_HSC_Applied> Tbl_OS_HSC_Applied { get; set; }
        public virtual DbSet<Tbl_OS_SSC> Tbl_OS_SSC { get; set; }
        public virtual DbSet<Tbl_OS_SSC_Applied> Tbl_OS_SSC_Applied { get; set; }
        public virtual DbSet<Tbl_Site_Block> Tbl_Site_Block { get; set; }
        public virtual DbSet<Tbl_SSC_Data> Tbl_SSC_Data { get; set; }
        public virtual DbSet<Tbl_SSC_Migration> Tbl_SSC_Migration { get; set; }
        public virtual DbSet<Tbl_SSC_Migration_Pri> Tbl_SSC_Migration_Pri { get; set; }
        public virtual DbSet<Tbl_SSC_Payment> Tbl_SSC_Payment { get; set; }
        public virtual DbSet<Tbl_SSC_Payment_Error> Tbl_SSC_Payment_Error { get; set; }
        public virtual DbSet<Tbl_SSC_Student_Subject> Tbl_SSC_Student_Subject { get; set; }
        public virtual DbSet<Tbl_SSC_SUB> Tbl_SSC_SUB { get; set; }
        public virtual DbSet<Tbl_SSC_UID> Tbl_SSC_UID { get; set; }
        public virtual DbSet<Tbl_SSC_Verification> Tbl_SSC_Verification { get; set; }
        public virtual DbSet<Tbl_SSC_Verification_Pri> Tbl_SSC_Verification_Pri { get; set; }
    
        public virtual int SP_INSERT_SSC_STUDENT_DATA(string aCTION, string seat_No, Nullable<int> div_code, Nullable<int> payment_Head, string unique_ID_Payment, string unique_ID_Seat_No, Nullable<int> pre_Ref_ID, ObjectParameter rESULT)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var seat_NoParameter = seat_No != null ?
                new ObjectParameter("Seat_No", seat_No) :
                new ObjectParameter("Seat_No", typeof(string));
    
            var div_codeParameter = div_code.HasValue ?
                new ObjectParameter("Div_code", div_code) :
                new ObjectParameter("Div_code", typeof(int));
    
            var payment_HeadParameter = payment_Head.HasValue ?
                new ObjectParameter("Payment_Head", payment_Head) :
                new ObjectParameter("Payment_Head", typeof(int));
    
            var unique_ID_PaymentParameter = unique_ID_Payment != null ?
                new ObjectParameter("Unique_ID_Payment", unique_ID_Payment) :
                new ObjectParameter("Unique_ID_Payment", typeof(string));
    
            var unique_ID_Seat_NoParameter = unique_ID_Seat_No != null ?
                new ObjectParameter("Unique_ID_Seat_No", unique_ID_Seat_No) :
                new ObjectParameter("Unique_ID_Seat_No", typeof(string));
    
            var pre_Ref_IDParameter = pre_Ref_ID.HasValue ?
                new ObjectParameter("Pre_Ref_ID", pre_Ref_ID) :
                new ObjectParameter("Pre_Ref_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_SSC_STUDENT_DATA", aCTIONParameter, seat_NoParameter, div_codeParameter, payment_HeadParameter, unique_ID_PaymentParameter, unique_ID_Seat_NoParameter, pre_Ref_IDParameter, rESULT);
        }
    
        public virtual int SP_INSERT_SSC_STUDENT_MIGRATION(string aCTION, string seat_No, Nullable<int> div_Code, string unique_ID_Payment, string unique_ID_Seat_No, Nullable<int> pre_Ref_ID, ObjectParameter result)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var seat_NoParameter = seat_No != null ?
                new ObjectParameter("Seat_No", seat_No) :
                new ObjectParameter("Seat_No", typeof(string));
    
            var div_CodeParameter = div_Code.HasValue ?
                new ObjectParameter("Div_Code", div_Code) :
                new ObjectParameter("Div_Code", typeof(int));
    
            var unique_ID_PaymentParameter = unique_ID_Payment != null ?
                new ObjectParameter("Unique_ID_Payment", unique_ID_Payment) :
                new ObjectParameter("Unique_ID_Payment", typeof(string));
    
            var unique_ID_Seat_NoParameter = unique_ID_Seat_No != null ?
                new ObjectParameter("Unique_ID_Seat_No", unique_ID_Seat_No) :
                new ObjectParameter("Unique_ID_Seat_No", typeof(string));
    
            var pre_Ref_IDParameter = pre_Ref_ID.HasValue ?
                new ObjectParameter("Pre_Ref_ID", pre_Ref_ID) :
                new ObjectParameter("Pre_Ref_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_SSC_STUDENT_MIGRATION", aCTIONParameter, seat_NoParameter, div_CodeParameter, unique_ID_PaymentParameter, unique_ID_Seat_NoParameter, pre_Ref_IDParameter, result);
        }
    
        public virtual int SP_INSERT_STUDENT_DATA(string aCTION, string seat_No, Nullable<int> div_code, Nullable<int> payment_Head, string unique_ID_Payment, string unique_ID_Seat_No, Nullable<int> pre_Ref_ID, ObjectParameter rESULT)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var seat_NoParameter = seat_No != null ?
                new ObjectParameter("Seat_No", seat_No) :
                new ObjectParameter("Seat_No", typeof(string));
    
            var div_codeParameter = div_code.HasValue ?
                new ObjectParameter("Div_code", div_code) :
                new ObjectParameter("Div_code", typeof(int));
    
            var payment_HeadParameter = payment_Head.HasValue ?
                new ObjectParameter("Payment_Head", payment_Head) :
                new ObjectParameter("Payment_Head", typeof(int));
    
            var unique_ID_PaymentParameter = unique_ID_Payment != null ?
                new ObjectParameter("Unique_ID_Payment", unique_ID_Payment) :
                new ObjectParameter("Unique_ID_Payment", typeof(string));
    
            var unique_ID_Seat_NoParameter = unique_ID_Seat_No != null ?
                new ObjectParameter("Unique_ID_Seat_No", unique_ID_Seat_No) :
                new ObjectParameter("Unique_ID_Seat_No", typeof(string));
    
            var pre_Ref_IDParameter = pre_Ref_ID.HasValue ?
                new ObjectParameter("Pre_Ref_ID", pre_Ref_ID) :
                new ObjectParameter("Pre_Ref_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_STUDENT_DATA", aCTIONParameter, seat_NoParameter, div_codeParameter, payment_HeadParameter, unique_ID_PaymentParameter, unique_ID_Seat_NoParameter, pre_Ref_IDParameter, rESULT);
        }
    
        public virtual int SP_INSERT_STUDENT_MIGRATION(string aCTION, string seat_No, Nullable<int> div_Code, string unique_ID_Payment, string unique_ID_Seat_No, Nullable<int> pre_Ref_ID, ObjectParameter result)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var seat_NoParameter = seat_No != null ?
                new ObjectParameter("Seat_No", seat_No) :
                new ObjectParameter("Seat_No", typeof(string));
    
            var div_CodeParameter = div_Code.HasValue ?
                new ObjectParameter("Div_Code", div_Code) :
                new ObjectParameter("Div_Code", typeof(int));
    
            var unique_ID_PaymentParameter = unique_ID_Payment != null ?
                new ObjectParameter("Unique_ID_Payment", unique_ID_Payment) :
                new ObjectParameter("Unique_ID_Payment", typeof(string));
    
            var unique_ID_Seat_NoParameter = unique_ID_Seat_No != null ?
                new ObjectParameter("Unique_ID_Seat_No", unique_ID_Seat_No) :
                new ObjectParameter("Unique_ID_Seat_No", typeof(string));
    
            var pre_Ref_IDParameter = pre_Ref_ID.HasValue ?
                new ObjectParameter("Pre_Ref_ID", pre_Ref_ID) :
                new ObjectParameter("Pre_Ref_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_STUDENT_MIGRATION", aCTIONParameter, seat_NoParameter, div_CodeParameter, unique_ID_PaymentParameter, unique_ID_Seat_NoParameter, pre_Ref_IDParameter, result);
        }
    
        public virtual int Sp_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Payment_Entry", clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    
        public virtual ObjectResult<Tbl_SSC_Payment> Fun_Sp_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_SSC_Payment>("Fun_Sp_Payment_Entry", clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    
        public virtual ObjectResult<Tbl_SSC_Payment> Fun_Sp_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19, MergeOption mergeOption)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_SSC_Payment>("Fun_Sp_Payment_Entry", mergeOption, clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    
        public virtual int Sp_HSC_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_HSC_Payment_Entry", clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    
        public virtual ObjectResult<Tbl_HSC_Payment_Error> Fun_Sp_HSC_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_HSC_Payment_Error>("Fun_Sp_HSC_Payment_Entry", clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    
        public virtual ObjectResult<Tbl_HSC_Payment_Error> Fun_Sp_HSC_Payment_Entry(string clientTxnId, string firstName, string email, string spRespStatus, string udf17, string udf18, string udf20, string udf19, MergeOption mergeOption)
        {
            var clientTxnIdParameter = clientTxnId != null ?
                new ObjectParameter("clientTxnId", clientTxnId) :
                new ObjectParameter("clientTxnId", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var spRespStatusParameter = spRespStatus != null ?
                new ObjectParameter("spRespStatus", spRespStatus) :
                new ObjectParameter("spRespStatus", typeof(string));
    
            var udf17Parameter = udf17 != null ?
                new ObjectParameter("udf17", udf17) :
                new ObjectParameter("udf17", typeof(string));
    
            var udf18Parameter = udf18 != null ?
                new ObjectParameter("udf18", udf18) :
                new ObjectParameter("udf18", typeof(string));
    
            var udf20Parameter = udf20 != null ?
                new ObjectParameter("udf20", udf20) :
                new ObjectParameter("udf20", typeof(string));
    
            var udf19Parameter = udf19 != null ?
                new ObjectParameter("udf19", udf19) :
                new ObjectParameter("udf19", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_HSC_Payment_Error>("Fun_Sp_HSC_Payment_Entry", mergeOption, clientTxnIdParameter, firstNameParameter, emailParameter, spRespStatusParameter, udf17Parameter, udf18Parameter, udf20Parameter, udf19Parameter);
        }
    }
}
