//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCDATA_1
    {
        public string DIV { get; set; }
        public string SCH { get; set; }
        public string SEAT { get; set; }
        public string NAME { get; set; }
        public string SUB1 { get; set; }
        public string MARK1 { get; set; }
        public string SUB2 { get; set; }
        public string MARK2 { get; set; }
        public string SUB3 { get; set; }
        public string MARK3 { get; set; }
        public string SUB4 { get; set; }
        public string MARK4 { get; set; }
        public string SUB5 { get; set; }
        public string MARK5 { get; set; }
        public string SUB6 { get; set; }
        public string MARK6 { get; set; }
        public string SUB7 { get; set; }
        public string MARK7 { get; set; }
        public string SUB8 { get; set; }
        public string MARK8 { get; set; }
        public string TOTAL { get; set; }
        public string OUTOF { get; set; }
        public string SIGN { get; set; }
        public string GRACE { get; set; }
        public string COURSE { get; set; }
        public string MOTHER { get; set; }
    }
}
