//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HSC_Verification
    {
        public int ID { get; set; }
        public string Seat_No { get; set; }
        public Nullable<int> Payment_Head { get; set; }
        public string Address { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string Delivery_Mode { get; set; }
        public Nullable<double> Charge { get; set; }
        public Nullable<double> Total_Payment { get; set; }
        public string SUB1 { get; set; }
        public string SUB2 { get; set; }
        public string SUB3 { get; set; }
        public string SUB4 { get; set; }
        public string SUB5 { get; set; }
        public string SUB6 { get; set; }
        public string SUB7 { get; set; }
        public string Unique_ID_Payment { get; set; }
        public string Unique_ID_Seat_No { get; set; }
        public string Case_No { get; set; }
        public Nullable<int> Div_Code { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Status { get; set; }
        public string Responce { get; set; }
        public Nullable<System.DateTime> Reply_DateTime { get; set; }
        public Nullable<int> Pre_Ref_ID { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
