//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SSC_UID
    {
        public int ID { get; set; }
        public string DIV { get; set; }
        public string SEAT { get; set; }
        public string SUB { get; set; }
        public string PAP { get; set; }
        public string UID { get; set; }
    }
}
