//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Div_Details
    {
        public int ID { get; set; }
        public string DIV_Initial { get; set; }
        public string Div_Code { get; set; }
        public string Div_Name { get; set; }
        public string Password { get; set; }
    }
}
