//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Migration
    {
        public int ID { get; set; }
        public string Case_No { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Address { get; set; }
        public string Mobile_No1 { get; set; }
        public string Mobile_No2 { get; set; }
        public string Seat_No { get; set; }
        public string Exam { get; set; }
        public string Year { get; set; }
        public string Marks { get; set; }
        public string Percentage { get; set; }
        public string Center_No { get; set; }
        public string Center_Name { get; set; }
        public string Index_No { get; set; }
        public string School_Name { get; set; }
        public string Copy_Status { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Unique_ID_Payment { get; set; }
        public string Unique_ID_Seat_No { get; set; }
        public Nullable<int> Div_Code { get; set; }
        public Nullable<int> Pre_Ref_ID { get; set; }
        public Nullable<System.DateTime> OnDateTime { get; set; }
        public string Email_ID { get; set; }
        public string Delivery_Mode { get; set; }
        public string Status { get; set; }
        public string Responce { get; set; }
        public Nullable<System.DateTime> Reply_DateTime { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
