//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OS_HSC
    {
        public string SEAT_NO { get; set; }
        public string EXAM_CODE { get; set; }
        public string DIVN_CODE { get; set; }
        public string SCHOL_NO { get; set; }
        public string SRNO { get; set; }
        public string STREAM { get; set; }
        public string CENTER { get; set; }
        public string SEX_CD { get; set; }
        public string CAST_CD { get; set; }
        public string MEDIUM { get; set; }
        public string FR_RPT_NOC { get; set; }
        public string RG_PR_IS { get; set; }
        public string EXM_NEXM { get; set; }
        public string TECH { get; set; }
        public string PH { get; set; }
        public string FORN { get; set; }
        public string NAME { get; set; }
        public string MNAME { get; set; }
        public string ELGB_NO { get; set; }
        public string ENROL_NO { get; set; }
        public string TOT_EXM { get; set; }
        public string SUB1 { get; set; }
        public string LANG1 { get; set; }
        public string SUB1TH1 { get; set; }
        public string SUB1OR1 { get; set; }
        public string MARK1 { get; set; }
        public string COND1 { get; set; }
        public string SUB2 { get; set; }
        public string LANG2 { get; set; }
        public string SUB2TH1 { get; set; }
        public string SUB2OR1 { get; set; }
        public string MARK2 { get; set; }
        public string COND2 { get; set; }
        public string SUB3 { get; set; }
        public string LANG3 { get; set; }
        public string SUB3TH1 { get; set; }
        public string SUB3TH2 { get; set; }
        public string SUB3PR1 { get; set; }
        public string SUB3PR2 { get; set; }
        public string MARK3 { get; set; }
        public string COND3 { get; set; }
        public string SUB4 { get; set; }
        public string LANG4 { get; set; }
        public string SUB4TH1 { get; set; }
        public string SUB4TH2 { get; set; }
        public string SUB4PR1 { get; set; }
        public string SUB4PR2 { get; set; }
        public string MARK4 { get; set; }
        public string COND4 { get; set; }
        public string SUB5 { get; set; }
        public string LANG5 { get; set; }
        public string SUB5TH1 { get; set; }
        public string SUB5TH2 { get; set; }
        public string SUB5PR1 { get; set; }
        public string SUB5PR2 { get; set; }
        public string MARK5 { get; set; }
        public string COND5 { get; set; }
        public string SUB6 { get; set; }
        public string LANG6 { get; set; }
        public string SUB6TH1 { get; set; }
        public string SUB6TH2 { get; set; }
        public string SUB6PR1 { get; set; }
        public string SUB6PR2 { get; set; }
        public string MARK6 { get; set; }
        public string COND6 { get; set; }
        public string SUB7 { get; set; }
        public string LANG7 { get; set; }
        public string SUB7TH1 { get; set; }
        public string SUB7TH2 { get; set; }
        public string SUB7PR1 { get; set; }
        public string SUB7PR2 { get; set; }
        public string MARK7 { get; set; }
        public string COND7 { get; set; }
        public string SUB8 { get; set; }
        public string LANG8 { get; set; }
        public string MARK8 { get; set; }
        public string SUB9 { get; set; }
        public string LANG9 { get; set; }
        public string MARK9 { get; set; }
        public string ABS_SUBJ { get; set; }
        public string RES_DEBAR { get; set; }
        public string TOTAL { get; set; }
        public string PERCENT { get; set; }
        public string PASS_FAIL { get; set; }
        public string GRADE { get; set; }
        public string GRACE { get; set; }
        public string SUBJ_OFFER { get; set; }
        public string SUBJ_PASS { get; set; }
        public string SUBJ_FAIL { get; set; }
        public string SEATOLD { get; set; }
        public string SESYR { get; set; }
        public string SPORT { get; set; }
        public string SPORTMARK { get; set; }
        public string MINORITY { get; set; }
        public string DOB { get; set; }
        public string AADHAR_NO { get; set; }
        public string M30 { get; set; }
        public string FLAG { get; set; }
        public string C_NullFlags { get; set; }
    }
}
