//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HSC_Division_Block
    {
        public int ID { get; set; }
        public Nullable<int> Division_ID { get; set; }
        public Nullable<int> Payment_Head { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
    }
}
