//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OS_SSC
    {
        public int id { get; set; }
        public string exam_code { get; set; }
        public string seat_no { get; set; }
        public string schol_no { get; set; }
        public string srno { get; set; }
        public string center { get; set; }
        public string sex_cd { get; set; }
        public string cast_cd { get; set; }
        public string ph_code { get; set; }
        public string medium { get; set; }
        public string fr_rpt_no { get; set; }
        public string rg_pr_is { get; set; }
        public string exm_nexm { get; set; }
        public string tech { get; set; }
        public string fg { get; set; }
        public string bdate { get; set; }
        public string totsube { get; set; }
        public string name { get; set; }
        public string mname { get; set; }
        public string eligno { get; set; }
        public string lang1 { get; set; }
        public string lang1a { get; set; }
        public string lang2 { get; set; }
        public string lang2a { get; set; }
        public string lang3 { get; set; }
        public string lang3a { get; set; }
        public string sub41 { get; set; }
        public string sub42 { get; set; }
        public string sub4a { get; set; }
        public string sub5 { get; set; }
        public string sub5a { get; set; }
        public string sub6 { get; set; }
        public string sub6a { get; set; }
        public string sub7 { get; set; }
        public string sub7a { get; set; }
        public string op2orsg { get; set; }
        public string op2la { get; set; }
        public string op1la { get; set; }
        public string schsubj1 { get; set; }
        public string schsubj2 { get; set; }
        public string schsubj3 { get; set; }
        public string l1w { get; set; }
        public string l1o { get; set; }
        public string l21w { get; set; }
        public string l21o { get; set; }
        public string l22w { get; set; }
        public string l22o { get; set; }
        public string l3w { get; set; }
        public string l3o { get; set; }
        public string l3i { get; set; }
        public string maths1 { get; set; }
        public string maths2 { get; set; }
        public string mathsi { get; set; }
        public string scithe1 { get; set; }
        public string scithe2 { get; set; }
        public string scipra1 { get; set; }
        public string scipra2 { get; set; }
        public string sosci1 { get; set; }
        public string sosci2 { get; set; }
        public string soscii { get; set; }
        public string opp1mark { get; set; }
        public string opp2mark { get; set; }
        public string opp3mark { get; set; }
        public string opp4mark { get; set; }
        public string ict1 { get; set; }
        public string ict2 { get; set; }
        public string schgra1 { get; set; }
        public string schgra2 { get; set; }
        public string schgra3 { get; set; }
        public string schgra4 { get; set; }
        public string condsub1 { get; set; }
        public string condsub2 { get; set; }
        public string condsub3 { get; set; }
        public string condsub4 { get; set; }
        public string condsub5 { get; set; }
        public string condsub6 { get; set; }
        public string tsubj1 { get; set; }
        public string tsubj2 { get; set; }
        public string tsubj3 { get; set; }
        public string tsubj4 { get; set; }
        public string tsubj5 { get; set; }
        public string tsubj6 { get; set; }
        public string tsubj7gr { get; set; }
        public string gtotal { get; set; }
        public string perc { get; set; }
        public string passfail { get; set; }
        public string grades { get; set; }
        public string absenti { get; set; }
        public string seatold { get; set; }
        public string sesyr { get; set; }
        public string filler { get; set; }
        public string sport { get; set; }
        public string sportmark { get; set; }
        public string grace { get; set; }
        public string ind { get; set; }
        public string sub1pf { get; set; }
        public string sub2pf { get; set; }
        public string sub3pf { get; set; }
        public string sub4pf { get; set; }
        public string sub5pf { get; set; }
        public string sub6pf { get; set; }
        public string subdrop { get; set; }
        public string outofmark { get; set; }
        public string tot500 { get; set; }
        public string tot550 { get; set; }
        public string tot650 { get; set; }
        public string perc500 { get; set; }
        public string perc550 { get; set; }
        public string perc650 { get; set; }
        public string meritperc { get; set; }
        public string minority { get; set; }
        public string t818283 { get; set; }
        public string art { get; set; }
        public string aadhar { get; set; }
        public string bplace { get; set; }
        public string div { get; set; }
        public string cata { get; set; }
        public string finalcata { get; set; }
    }
}
