//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student_Subject_1
    {
        public int ID { get; set; }
        public string Seat_No { get; set; }
        public string Case_No { get; set; }
        public string Head { get; set; }
        public string Sub_Code { get; set; }
        public Nullable<int> Actual_Marks { get; set; }
        public Nullable<int> Update_Marks { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
